# Generated by Django 2.2.5 on 2020-07-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
    ]
