# Generated by Django 2.2.5 on 2020-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
