# Generated by Django 2.2.5 on 2020-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200724_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='award',
            name='description',
            field=models.TextField(default='some award'),
        ),
    ]
